name: RadQuest
description: "A learning app for Radiography students."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  bonfire: ^3.9.1
  flame_bloc: ^1.11.1
  flame_jenny: ^1.0.0
  flame_tiled: ^1.20.1
  flame_audio: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/tiled/
    - assets/images/characters/
    - assets/images/objects/
    - assets/sfx/
    - assets/audio/
    - assets/audio/bgm.mp3


  fonts:

    - family: Minecraft
      fonts:
        - asset: assets/fonts/minecraft.ttf

    - family: VT323
      fonts:
        - asset: assets/fonts/VT323-Regular.ttf

